#!/bin/bash

if [ -e "/etc/colorsdef" ]; then

        source /etc/colorsdef

        if [[ ${EUID} == 0 ]] ; then
                PS1="${debian_chroot:+($debian_chroot)}\[${BRED}\]\u\[${COLOR_OFF}\]@\[${ON_RED}\]\h\[${COLOR_OFF}\] [\[${BCYAN}\]\w\[${COLOR_OFF}\]] [\[${BPURPLE}\]\t\[${COLOR_OFF}\]]\n\$ "
        else
                PS1="${debian_chroot:+($debian_chroot)}\[${BGREEN}\]\u\[${COLOR_OFF}\]@\[${ON_RED}\]\h\[${COLOR_OFF}\] [\[${BCYAN}\]\w\[${COLOR_OFF}\]] [\[${BPURPLE}\]\t\[${COLOR_OFF}\]]\n\$ "
        fi
else

        if [[ ${EUID} == 0 ]] ; then
            PS1='${debian_chroot:+($debian_chroot)}\[\e[1;31m\]\u\[\e[m\]@\[\e[41m\]\h \[\e[m\][\[\e[1;36m\]\w\[\e[m\]] [\[\e[35;1m\]\t\[\e[m\]]\n\$ '
        else
            PS1='${debian_chroot:+($debian_chroot)}\[\e[1;32m\]\u\[\e[m\]@\[\e[41m\]\h \[\e[m\][\[\e[1;36m\]\w\[\e[m\]] [\[\e[35;1m\]\t\[\e[m\]]\n\$ '
        fi
fi
