#!/bin/bash

# check for git-prompt and export variables for automatic git
# repository information on the command line prompt.sh
if [ -f "/usr/share/git/completion/git-prompt.sh" ]; then
	source "/usr/share/git/completion/git-prompt.sh"
	export GIT_PS1_SHOWDIRTYSTATE="true"
	export GIT_PS1_SHOWSTASHSTATE="true"
	export GIT_PS1_SHOWUNTRACKEDFILES="true"
	export GIT_PS1_SHOWUPSTREAM="auto"
fi

# get a nice prompt with the git info
if [[ ${EUID} == 0 ]] ; then
        PS1='\[\e[1;31m\]\u\[\e[m\]@\[\e[1;34m\]\h \[\e[m\][\[\e[1;36m\]\w\[\e[1;33m\]$(__git_ps1 " %s")\[\e[m\]]\n\$  '
else
        PS1='\[\e[1;32m\]\u\[\e[m\]@\[\e[1;34m\]\h \[\e[m\][\[\e[1;36m\]\w\[\e[1;33m\]$(__git_ps1 " %s")\[\e[m\]]\n\$ '
fi
